config/routes.rb
Rails.application.routes.draw do
  resources :entries
  
  root 'entries#index' #root

  get 'index', to: 'entries#index' #no params, default values
  get 'index/:offset', to: 'entries#index' #offset specified
  get 'index/:offset/:number_of_entries', to: 'entries#index' #offset and number of entries specified
 
end

app/models/entry.rb
class Entry < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end
  
  def get_rank
    @entries = Entry.all
    @entries.order!("score desc")
    
  end

  # GET /entries/new
  def new
   @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    if not (Entry.find_by(name: params[:entry][:name]))

      @entry = Entry.new(entry_params)
      
      @entries = Entry.all
      @entries.order!("score desc")
      
      respond_to do |format|
        if @entry.save
          
          format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
          format.json { render :show, status: :created, location: @entry }
        else
          format.html { render :new }
          format.json { render json: @entry.errors, status: :unprocessable_entity }
        end
      end
    else
      Entry.find_by(name: params[:entry][:name]).update_attributes(:score => params[:entry][:score])
      
      @entries = Entry.all
      @entries.order!("score desc")
      
      redirect_to Entry.find_by(name: params[:entry][:name]), notice: 'User score updated!'
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:name, :score)
    end
    
    def index_params
      params.permit(:offset, :number_of_entries)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing Entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<p id="notice"><%= notice %></p>
<% @entries = Entry.all %>

<%# CHECK FOR NUM ENTRIES %>
<% if not params[:number_of_entries] %>
  <% @numEntries = 10 %>
<% else %>
  <% @numEntries = params[:number_of_entries].to_i %>
  <%if @numEntries > 100 || @numEntries < 1 %> <%# INVALID NUMBER %>
    <% @numEntries = 10 %>
  <% end %>
<% end %>


<%# CHECK FOR OFFSET %>
<% if not params[:offset] %>
  <% @offset = 0 %>
<% else %>
  <% @offset = params[:offset].to_i - 1 %> <%# to allow for array 0 offset %>
  <%if @offset > @entries.count %> <%# INVALID NUMBER %>
    <% @offset = 0 %>
  <% end %>
<% end %>

<h1>Listing Entries</h1>

<table>
  <thead>
    <tr>
      <th>Rank</th>
      <th>Name</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.order!("score desc").offset(@offset).take(@numEntries).each do |entry| %>
      <tr>
        <td><%= @entries.find_index(entry) + 1 %></td> <%#added one to offset zero starting index for array%>
        <td><%= entry.name %></td>
        <td><%= entry.score %></td>
        <td><%= link_to 'Show', entry %></td>
        <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Unfiltered Top 10', index_path %><br>
<%= link_to 'New Entry', new_entry_path %>

app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @entry.name %>
</p>

<p>
  <strong>Score:</strong>
  <%= @entry.score %>
</p>

<p>
  <strong>Rank:</strong>
  <% @entries = Entry.all %>
  <% @entries.order!("score desc") %>
  <%= @entries.index.find_index(@entry) + 1 %>
</p>

<%= link_to 'Back', entries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Leaderboard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <strong>FOR INTERNAL USE ONLY - GERALD ROYBAL III 2014</strong>

  <%= yield %>

</body>
</html>